name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the JVM maximum heap limit
  MAVEN_OPTS: -Xms512m -Xmx1024m

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -B install -DskipTests -Dmaven.javadoc.skip=true dependency:go-offline

    - name: Test
      run: mvn -B -Dmaven.javadoc.skip=true verify

    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
